name: Multiple Machine Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x]
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{matrix.platform}}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - uses: actions/checkout@v2

      - name: Test
        run: go test -v mes/tests
